name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build -Partifact_version=${{ github.ref_name }}

      - name: Run publish
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.KEY }} -Pgradle.publish.secret=${{ secrets.SECRET }} -Partifact_version=${{ github.ref_name }}

      - name: Debug Releases
        run: gh release list

      - name: Create Release and Upload Jar
        run: |
            gh release create ${{ github.ref_name }} -t "Release v${{ github.ref_name }}"
            gh release upload ${{ github.ref_name }} build/libs/github-gradle-${{ github.ref_name }}.jar
            gh release upload ${{ github.ref_name }} build/libs/github-gradle-javadoc-${{ github.ref_name }}.jar
            gh release upload ${{ github.ref_name }} build/libs/github-gradle-main-${{ github.ref_name }}.jar
            gh release upload ${{ github.ref_name }} build/libs/github-gradle-sources-${{ github.ref_name }}.jar
